apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: strava
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.1.2"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: strava
    image:
      name: vibioh/strava
      tag: "202402262320" # {"$imagepolicy": "default:flux-strava-api:tag"}
    labels:
      tags.datadoghq.com/env: "production"
      tags.datadoghq.com/service: "strava"
      tags.datadoghq.com/version: "202402262320" # {"$imagepolicy": "default:flux-strava-api:tag"}
    env:
      - name: GOMAXPROCS
        valueFrom:
          resourceFieldRef:
            resource: limits.cpu
      - name: GOMEMLIMIT
        valueFrom:
          resourceFieldRef:
            resource: limits.memory
      - name: VERSION
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/version']
      - name: OTEL_SERVICE_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/service']
    config:
      OTEL_RESOURCE_ATTRIBUTES: env=production,git.repository_url=github.com/ViBiOh/strava
      STRAVA_ACCESS_TOKEN: pk.eyJ1IjoidmliaW9oIiwiYSI6ImNqMzFmbTFoOTAwMWMycW82YXppbGRidXAifQ.bb6xyGsr1kQW3UozHS2Pmw
      STRAVA_LOGGER_JSON: "true"
      STRAVA_PUBLIC_URL: https://strava.vibioh.fr
      STRAVA_TELEMETRY_URL: datadog.observability:4317
    secrets:
      STRAVA_CLIENT_ID: AgAzHYRL/0Aae2tc4ewealxemxNJ5Wor5roBiVzYi3TXbexG1sfmsXsYBSoar7Qif+sLo4ru+r0dYNsZFvxApSA7pB3WVRdS1cfiSubf15mojkloz5/1fCLpxuXHlHm3idwObBiaevPlOtaL+sJuFKY9VGOhQjeMq8kZSxqKYYQ7jKDx2/vrO/Orv89OM7v/dDRLxf/AQqn3iDfLtmju0wtiFKia4W+JtaOAOn3eo/56R8QsuqeZfHiZWfTBmgZ37ZUQWAfbULxTvAf8TbFJICuklg9bATr4Hpcta7A4yVjyS7uS9188o1d+wZtOpLVQqEOr6kdMQmKMEmXCleWM2JgVHzb49addKxj89MiY1z0au63SGQiZzVGvEWxw0b7CxKNU4/ZBjodMCEOU2oV1BZ3jmEst6yy539mcNGkEi743/DBWdsy3cSld1/4CqBN1MVQMrlqqaQyva7gukSIWS9jQlIcfMVSUy6bqF91ABdZ7S8Z0XI9llI5W5wQLy9LkLDA9fYcHfhsyx56/yAKTZNz88exezRYGZth2cSuiPxBIbL4BZToLKbEWv1N6B6E0CNLG0an4w5JQnDRFdzUpbgS1feosVQpv+aosqG/Ai2rlh27rt3mP7sOSVl6lO2cnQfKKgWQ10BjlvKR+U7NMMq4Gr6w0jPmQB8LApmnG3gIvmGYOHq0vFeLwwoN3tp67QIDK4Eq2S0U=
      STRAVA_CLIENT_SECRET: AgCIAe+wtO6CyMW0gpEjYmeAtXrlstIvhMSbmxWPhH2ttHnErKXTRh6oRSPMyvvg9n5vPlwZ16e66jSr1zPFc7cmIJvFWe7tyB1OACaXHtPsgC0FA4SnhUc6CaZjZmU4oPF91lXo1Et9NPb5H+1Yckj+sBNdCOIe5h8+ULocbMi7agipOX2exxZ+TGicQrw83KepgaJg103bzIuk31Nmhddsx5pH28NlSuy8ZJacb8JE4WWKvGvR8yXlZT8i/37Gp28BFkolVbMbdFVRFapBaRrqkM2pqasa7tsAVTaCjI1PMHqbPpUvJ3rjrwAzH1CdaV0U4zkZEoIWa16dqh0SHCgYze5LaUgzbW3wc5XaZPcKPIKCXVB8wIOT3ypaK0vV3+PTf5tQ2g1tR7GAORfxXOraG7QD12xUzuwfPQzIfz9tyOY14rpMi4SaLS6BE30hW/fjvP5X5jYp45u4QvcpFenGDIb+lgEFynpd5sAbY4+Fks5/lCumzTN5QBjUwDS2qdpMcFmaTVxhoQ1sWqTxw/PtVkLiy25/TLvs02T12GEAt1h+sSbAOkhv59DyO1itflMWLuiQSxLDyzoJZm09rhRU0rjJuvzkNqjE4po9+8zqjXRz2a3KZYJp1rXNRQNako4Dp6ZwiX0akG+6L8Kk/yFrn4ZxIsL5j0GACKYNJiaWZa2pPZMUYQkkkbQJesLgKoVXwRyHQltzFD7/CItko8LPoL/zPtsB1mWSrGy6HSWRrJkVyHsUO4UZ
    pprof:
      enabled: true
