apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: commute
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.1.2"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: commute
    image:
      name: vibioh/commute
      tag: "202405071936" # {"$imagepolicy": "default:flux-commute-api:tag"}
    labels:
      tags.datadoghq.com/env: "production"
      tags.datadoghq.com/service: "commute"
      tags.datadoghq.com/version: "202405071936" # {"$imagepolicy": "default:flux-commute-api:tag"}
    env:
      - name: GOMAXPROCS
        valueFrom:
          resourceFieldRef:
            resource: limits.cpu
      - name: GOMEMLIMIT
        valueFrom:
          resourceFieldRef:
            resource: limits.memory
      - name: VERSION
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/version']
      - name: OTEL_SERVICE_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/service']
    config:
      COMMUTE_LOGGER_JSON: "true"
      COMMUTE_MAPBOX_ACCESS_TOKEN: pk.eyJ1IjoidmliaW9oIiwiYSI6ImNqMzFmbTFoOTAwMWMycW82YXppbGRidXAifQ.bb6xyGsr1kQW3UozHS2Pmw
      COMMUTE_PPROF_AGENT: http://datadog.observability:8126
      COMMUTE_PUBLIC_URL: https://commute.vibioh.fr
      COMMUTE_TELEMETRY_URL: datadog.observability:4317
      OTEL_RESOURCE_ATTRIBUTES: env=production,git.repository_url=github.com/ViBiOh/commute
    secrets:
      COMMUTE_STRAVA_CLIENT_ID: AgAk5OcuIvcCxMiB9xvn5+jttopqFAFAUcSND4tbwWuaFq14VylLth8xZu+Rvx8vS5WN/Vxh25tXOrHHrvZPpdEV9rFVGvZtzIAQk63zVeaAnP82Z7IaMFERE89zKUPxOvmWhJPDugj17fRt3JpQZZ5wB/lZ19aruK0E8LIx9QBjqGrTy7bShPlDVWbnqxuGDRY+5afWs2BxKmDHku3LFK5FGIXfMZ8I221tKfuC3Yig0v7b/U3iY130T01r7UkH7JdZS6PKaaIOG70so8Rq7dajiMtB5qK+z7UQ9gGzcabqIdKYWJZs9xqnEjIR1/IuWlXq6F6/2bF5turTGePmtd9uNEUGw6vpNeWqcxD/oM+v/J91D95G5GXJHuKiqS8D9tGsIm23fUtkAfDdGrdYYkRMuLSOBsW1pVlQT2nxkVkz1+7B/PEAk/JYdIDHpcmjCmCU4ADBkVi8MM+rHlvHHBp9Jq2o928M9OFFXvCdLlF0ZGQuyZyfUq49ERmPKHZkZbbQOJ+xWnLapO8bMCtC9vVfBh8blh+tXcWr4n36H2E7KVo5QqbQWMu2aKPx6rGLwXnPOA+WyHi7fQAY80cqQ31rtEBmf7mI/hxUmT7wq0Bzw4sGq6yx9t9JcdM+FLJycEtZJiek/YWJrAQasntGkZ9sKrEKQNcT0uoUtApLdygXKSw4zrJE9ZyGGUR5bin4WPnKpsczSao=
      COMMUTE_STRAVA_CLIENT_SECRET: AgChrnm4LIVo/slVf35EF4NRpW2rC9FPrbtVumZqmt47msO5baOQ408fa5RZru/dQoRA04kl3XUH/MNQpQqywiAfusWG9JcFKZpM3C0Nd1Dlx6HxofrhftUPf6tPt2dr5bZdG9ZG5lN0L/amDkN926TM7gINsfIWtJGU5CiBm1z/uzjRbvuc8OqBFIFKk14On7JdLGaB5Um6/sgWl7QE1Z45jsJFjj+PAafZjjQEiXdKBw7Q9Rt1WZkq8w3yeiGWct4xM1UX1rInj21zUJ24l7I4PnFjqDUG2CL5mWPTD+Avt2ciB3tXDBBM986p5cHQzV0yrj4thch1cFSRyELequt+SXh9A7V15yT6TPLIMx+Ag5sh9okrn5zLaCBGDzvnl0io05elnJ9HmsJrSJg9dlDuiOWLRYj8bOqrvVp6zOj7tdcefvFn+4uIilmeNvyj+pBm3J0nnpqNM/w0Wn84lqZFgCXeENqs0o/eXY7UduRk7Xhoja554SIXaXO/bEdZBtkRR/+CpD/TaYMeNFAObLzdGhfrVciDCZkqB4oh5SJwIEghk0wP9jrWVK7Sr1ja6bCkvA3p5GL97V1/l3PNzV9Lqlqq2/SrUtS0zEvryCtiY+FnMSur9p09SNs2Rwmvh30Mhy9FjnNhc4hV5uugh873bD3RRuZqF9YwC9FVgUktBJ5Yl/RgihuhqChd4tO1diBZF5pQvS1RrBx5wZdVOqoMGM4SyAtJs7BuKEd7zydzCf9fnRcUXf/2
      COMMUTE_WAHOO_CLIENT_ID: AgAOev50jKy9GXcQ6P7GlvHPahpcDenz+KRnaqc8TOXOzpd4OX0vX4tUimFiHbegNpyeckq9NTg4teSXZisHUoLcZeD0bfafeTFo8iyacOUaYq/MDVWp3gkGNIk6RU2got0MSWM5/j+ja4BfMzIiLfuHkKbkNDDqsCltRp0Ww5Fqez1Yh1RrCblNxtsPVFexWxiruo8r+xr1n/DRL+drL6eNtaJCEgz0jpIv7ckUftWebxVrbG4pBAhsJC2oS3mxMMV0AugQoBCShIXJppIbd/f2vHL4oDBNPOXqc5ydF/uFBJrghK1RNmslfGYPBvutvRuvTY30K8sKB2MeU+nwMZd52CQJJgyOLwK+crZFEFHbrXSKlYnbCWgEEjsV+cSEZ8jc2Nfa7FedBRtRqoy5+p00Otqg9wmRq/NYB4N34Rccsi3Mv8UFR70XplDVjtkBA4DtNXvLDcVC1YtcLKET/UA3dL3PbUegIpe1mRP+EZ6kwgc/EoPfG7lJTAMMT6XlbY3RFkeBlR7oP9t+Bjx9Go5WfACMgYEM8amhWryBa001F7I651MXAgkIeIsZ81QPqUAkuXMQUIcStJhDMRsdl9wxfw2hnG7FJPN2N++uD5qj+6t2Bmgu3WhvjRu1oTXyzIcYgSavEUNW33OHKJr4RhiLJaLrjuipLDWcTZorjMcyPSg+AOMonMZgysK/qqEehsXg1XbI2O4+zZNaMs/Lgos78jFEKHQbmSibnJnFHtl4WyZE1rkkpkL+akvb
      COMMUTE_WAHOO_CLIENT_SECRET: AgA0ryRIJ/Vmb0sWZ+UKKiiSJd4Kx9gLutpmfPrmP99NDoOWK/pE9Ee2vSCG0CoNC2sPA/qcP2O1s1bs2B1PRlERUVL4/Oz3xKbvW2D1EYQy7/LFpi1f1gnkTr+o1J2RBnF2rwLjcj+OAIyIQyznIqYcwV2E2xIr+P3PEfPWxxn37oLb6JlBhTCYRj9pFIz3HWrb4s3dYYZ+T/hfGFIfaV3zBXRlYSX+P9Jn7tFhdqzUui63qlpAaWbwLgS4LY55EAc5kohkfOrBwpPiLpL2Hh4FakVXlfG2p8UjcXnH8iz5LY5Jc8gNjWb4s7Lg85sqtoFe5xMswLiX1Uur8fBlq/uwqP2/KXLTF7lRaKM9MCEZkRAKP3k2a5NEzJf+A8QR5xzGsnTm9J6jkyjTKXE9nc3Cnh+Jco+nV2qgBIeVqlcJ6FE6vhKRgVLz50U5ixHEBcEWM7rtMDxU5+pOwwsHGtTA3UysP5/VkhHx6z/tWgc9dyAVN9dJzuWAB0V7ArNxKwyxY78prhnhiA6KlhTh4DAdJPWZtX65QXOsr54XNh9o3wYoHmQgUOxluh6P/qKLOUWVP3rEVfcPe4T4izkL6P6RtD02wRzQa3fnDSNcLIOvpJRrDz5Eeav7MJ/lr/95r00AWAH2eo0NgecjMSDngewILSx+WIEdiGMfN+LK7BX8bSLHN1cR/Ds/Ld5aRUvZ+YUXo/zSJfTWyiT20rk0PwSSfM44hGp+NmGo6TiNGIytsisQvnrQ4QmqgemE
    autoscaling:
      enabled: false
